a = int(input("The ​initial B bacteria number: "))
b = int(input("A period of time: "))
print(f'How much B bacterias are there? {a}')
print(f'How much time in minutes we will wait? {b}')
print(f'After {b} minutes, we would have {a * b} bacterias')